name: Test CI

on: [push, pull_request]

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Lint check the project
              run: pnpm lint

            - name: Test for the prettier format
              run: pnpm fmt

            - name: Build the project and type check
              run: pnpm build
